---
NEED_MXNET: True # recommend 1.3.1
NEED_PYTORCH: True # recommend 0.4.1

DETECT_MODEL: "FPN"
ALIGN_MODEL: "ONET"
RECOGNIZE_MODEL: "ARCFACE"

# Turn on this option when first run the code, preprocessing the ID images
# Turn off it to save time if you have already run the codes
DATABASE_READY: False
# The original folder contains ID images
ID_FOLDER: "/home/liwen/src/face_detect_recognize/id_img"
# The folder contains algined ID images
ALIGNED_FOLDER: "/home/liwen/src/face_detect_recognize/id_img_aligned"

DETECT:
    SCALE: # adjust according to your input to have better efficiency and performance
    - 300 # shorter side limit
    - 500 # longer side limit
    THRESH: 0.7
    SYMBOL_PATH: "/home/liwen/src/face_detect_recognize/lib/data/fpn_widerface-symbol.json"
    MODEL_PATH: "/home/liwen/src/face_detect_recognize/lib/data/fpn_widerface"
    GPU_ID: 0
    FONT_PATH: "/home/liwen/src/face_detect_recognize/lib/data/simsun.ttc" # This actually is a font file for showing Chinese in pictures

ALIGN:
    THRESH: 0.3
    MODEL_PATH: "/home/liwen/src/face_detect_recognize/lib/data/det3"
    GPU_ID: 0

RECOGNIZE:
    STANDARD: "MSE" # "MSE mean square erro, "COSINE" cosine distance
    THRESH: 1.24 # 1.24 is recommended for MSE, 0.5 may be good for COSINE
    BATCH_SIZE: 8 # depends on the memory size of your GPU, I think 8 is good enough
    MODEL_PATH: "/home/liwen/src/face_detect_recognize/lib/data/model"
    GPU_ID: 0